system: exercise

service: mariadb-service

deployment:
  image:
    repository: tferrari92/mariadb-service
    
  labels:
    system: exercise
    service: mariadb-service
    # backstage.io/kubernetes-id: mariadb
