apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}-service
spec:
  selector:
    app: {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP